### ISSUE TITLE
Lumen support?

### ISSUE THREAD

**Issue by bretenatorCL** [JayBizzle/Laravel-Migrations-Organiser#15]
I have a Lumen project where I would like to use this package. I will admit I'm fairly new to Laravel. I can install and run this package just fine in a Laravel project but, in Lumen it gives me the following error when I just list the artisan commands:

```
"[ErrorException]
  Argument 2 passed to Jaybizzle\MigrationsOrganiser\Commands\MigrateOrganise::__construct() must be an instance of Jaybizzle\MigrationsOrganiser\Migrator, instance of Illuminate\Database\Migrations\Migrator given, called in /var/www/
  migrationTest/vendor/jaybizzle/laravel-migrations-organiser/src/MigrationsOrganiserServiceProvider.php on line 38 and defined"
```

It gives a similar error for the MigrateDisorganise command too. Would if be fairly easy to get this working for Lumen as well?

Thanks.

**Comment by JayBizzle** [comment]
Hi,

We don't and haven't used Lumen, but I will have a look into it over the next couple of days and see if we can get it to work.

Thanks

**Comment by bretenatorCL** [comment]
Thanks for taking a look. I appreciate it.

Bret Westenskow
IT Director

bret.westenskow@clearlink.com
Office - 801 937-6969
Mobile - 801 232-7635
www.clearlink.com     LinkedIn
<http://www.linkedin.com/company/100451?trk=saber_s000001e_1000>

This electronic message and any attachments hereto contain information
which may be privileged, confidential, or otherwise protected from
disclosure. The information is intended to be for the addressee only. If
you are not the addressee, any disclosure, copy, distribution or use of the
contents of the message or any attachments hereto is strictly prohibited.
If you have received this electronic message in error, please notify us
immediately, and permanently delete the original message and attachments.

**Comment by JayBizzle** [comment]
Had a quick look into this and I was hoping with a few tweaks I could get this to work, but it looks like it needs a from scratch approach.

I'm still interested in doing this, but as we don't currently use Lumen on any production sites, this will be low priority for me.

I will get round to it at some point though.

**Comment by bretenatorCL** [comment]
Ok. Thanks for taking look at it. If you do get it implemented at some
point, please let me know.

Bret Westenskow
IT Director

bret.westenskow@clearlink.com
Office - 801 937-6969
Mobile - 801 232-7635
www.clearlink.com     LinkedIn
<http://www.linkedin.com/company/100451?trk=saber_s000001e_1000>

This electronic message and any attachments hereto contain information
which may be privileged, confidential, or otherwise protected from
disclosure. The information is intended to be for the addressee only. If
you are not the addressee, any disclosure, copy, distribution or use of the
contents of the message or any attachments hereto is strictly prohibited.
If you have received this electronic message in error, please notify us
immediately, and permanently delete the original message and attachments.
