### ISSUE TITLE
Laravel 5.6

### ISSUE THREAD

**Issue by dmitryuk** [JayBizzle/Laravel-Migrations-Organiser#23]
Can't be installed with fresh Laravel 5.6
 - Installation request for jaybizzle/laravel-migrations-organiser ^4.1 -> satisfiable by jaybizzle/laravel-migrations-organiser[v4.1.0, v4.1.1].
    - Conclusion: don't install laravel/framework v5.6.0
jaybizzle/laravel-migrations-organiser v4.1.0 requires illuminate/support 5.3.*|5.4.*|5.5.* -> satisfiable by laravel/framework[5.3.x-dev, 5.4.x-dev, 5.5.x-dev], illuminate/support[5.3.x-dev, 5.4.x-dev, 5.5.x-dev, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35].
I have made pull request
https://github.com/JayBizzle/Laravel-Migrations-Organiser/pull/24

**Comment by xakzona** [comment]
I have made pull request
https://github.com/JayBizzle/Laravel-Migrations-Organiser/pull/24

**Comment by JayBizzle** [comment]
Fixed in #24
