### ISSUE TITLE
Not able to rollback migrations.

### ISSUE THREAD

**Issue by asachanfbd** [JayBizzle/Laravel-Migrations-Organiser#26]
version 3.*

**Comment by JayBizzle** [comment]
More info please...

**Comment by asachanfbd** [comment]
I have laravel 5.2 installed and installed 3.* of this repo. Organize/create worked perfectly. But when tried artisan migrate:rollback it failed with the message "migration file not found". I guess command rollback is not modified according to new file system.

**Comment by JayBizzle** [comment]
I'll take a look into it if I get chance. Having said that, we no longer use 5.2 in any projects so I don't have a real urge to do this any time quickly so if your willing to look into it yourself and maybe create a PR, that'd be great.

Thanks :+1:
