### ISSUE TITLE
Laravel 5.7.3 Cannot install laralve-migrations-organiser

### ISSUE THREAD

**Issue by RhRU** [JayBizzle/Laravel-Migrations-Organiser#27]
Long story short
Tried updating from laravel 5.6.* to laravel 5.7
Even tried via require, and adding it manually to composer.json
Always the same message:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install jaybizzle/laravel-migrations-organiser v4.1.2
    - Conclusion: don't install jaybizzle/laravel-migrations-organiser v4.1.1
    - Conclusion: don't install jaybizzle/laravel-migrations-organiser v4.1.0
    - Conclusion: don't install jaybizzle/laravel-migrations-organiser v4.0.3
    - Conclusion: don't install jaybizzle/laravel-migrations-organiser v4.0.2
    - Conclusion: don't install jaybizzle/laravel-migrations-organiser v4.0.1
    - Conclusion: remove laravel/framework v5.7.3
    - Installation request for jaybizzle/laravel-migrations-organiser 4.* -> satisfiable by jaybizzle/laravel-migrations-organiser[v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.1.0, v4.1.1, v4.1.2].
    - Conclusion: don't install laravel/framework v5.7.3
    - jaybizzle/laravel-migrations-organiser v4.0.0 requires illuminate/support 5.3.* -> satisfiable by laravel/framework[5.3.x-dev], illuminate/support[5.3.x-dev, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - illuminate/support 5.3.x-dev conflicts with laravel/framework[v5.7.3].
    - illuminate/support v5.3.0 conflicts with laravel/framework[v5.7.3].
    - illuminate/support v5.3.16 conflicts with laravel/framework[v5.7.3].
    - illuminate/support v5.3.23 conflicts with laravel/framework[v5.7.3].
    - illuminate/support v5.3.4 conflicts with laravel/framework[v5.7.3].
    - laravel/framework 5.3.x-dev conflicts with laravel/framework[v5.7.3].
    - Installation request for laravel/framework (locked at v5.7.3, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.3].

Installation failed, reverting ./composer.json to its original content.`

**Comment by JayBizzle** [comment]
Thanks for reporting.

I updated last week for Laravel 5.7 but forgot to tag a release.

Try now, should be sorted 👍

**Comment by RhRU** [comment]
Works like a charm thx.
I saw that you updated for 5.7 so that was really odd.
Keep up the good work! I use this plugin on all of my projects!!
