### ISSUE TITLE
Carbon 2

### ISSUE THREAD

**Issue by forxer** [JayBizzle/Laravel-Migrations-Organiser#29]
Would it be possible to update the Carbon dependency to use version 2?

**Comment by JayBizzle** [comment]
Yes, can't see why not. If you have time to do a PR to allow v1 and V2 that'd be great, otherwise I'll get it done in the next few days 👍

**Comment by JayBizzle** [comment]
Were you having a specific problem with this. Just realised that the Carbon dependency it in the `require-dev` section, which shouldn't affect a normal installation.

Having said that, the Carbon requirement isn't actually needed, so I have removed it from the `composer.json`

Thanks
