### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by bcorcoran** [JayBizzle/Laravel-Migrations-Organiser#31]
Can you please make a new release that includes Laravel 7 support? I see it's updated on master.

**Comment by JayBizzle** [comment]
Ive published `v4.3.0`.

Give it a try and let me know how you get on as I haven't had time to fully test it myself.

Thanks 👍

**Comment by skyrpex** [comment]
It's really close, it just needs to update `MigrationCreator`:

https://github.com/JayBizzle/Laravel-Migrations-Organiser/blob/f2e67b7be574528c11106e21a7842b7ffa30f047/src/MigrationsOrganiserServiceProvider.php#L22.

**Comment by skyrpex** [comment]
Not sure if this solution breaks compatibility with older Laravel releases.

**Comment by JayBizzle** [comment]
Awesome. Thanks for this. What I will do is revert the 4 branch and release a version 5 that is compatible with L7 👍

**Comment by bcorcoran** [comment]
Thanks! Adding null as the second arg seems to work fine.
