### ISSUE TITLE
Laravel 9 support please

### ISSUE THREAD

**Issue by adrienne** [JayBizzle/Laravel-Migrations-Organiser#44]
@JayBizzle please fix composer.json for Laravel 9 support?

**Comment by JayBizzle** [comment]
We should get round to this in a week or so unless someone beats me to it 👍🏻

**Comment by adrienne** [comment]
Any luck?

**Comment by JayBizzle** [comment]
Not got round to it yet, we should get to it next week 🤞🏻

**Comment by JayBizzle** [comment]
Done - https://github.com/JayBizzle/Laravel-Migrations-Organiser/releases/tag/v6.2.0
